package me.reply.app.data

import javax.inject.Inject
import javax.inject.Singleton

/**
 * The single source of truth for all message-related data.
 * This is the "kitchen assistant". It's the only class that is allowed to
 * talk directly to the "librarian" (the MessageDao).
 * The ViewModel will only ever talk to this repository, never the DAO directly.
 * Hilt's @Inject constructor tells it how to build this class automatically.
 */
@Singleton
class MessageRepository @Inject constructor(private val messageDao: MessageDao) {

    /**
     * Provides the live stream of contact names to the ViewModel.
     */
    fun getImportedContacts() = messageDao.getImportedContacts()

    /**
     * Retrieves the full chat history for a specific contact.
     */
    suspend fun getAllMessagesForContact(contactName: String): List<Message> {
        return messageDao.getAllMessagesForContact(contactName)
    }

    /**
     * A powerful function that first inserts new messages and then immediately
     * fetches them again. This is crucial because it ensures the Message objects
     * returned have the correct, unique IDs that were just generated by the database.
     */
    suspend fun insertAndGetMessages(messages: List<Message>): List<Message> {
        val newIds = messageDao.insertAndGetIds(messages)
        // We only fetch the messages for the new IDs that were successfully inserted.
        if (newIds.isNotEmpty()) {
            return messageDao.getMessagesByIds(newIds)
        }
        return emptyList()
    }

    /**
     * Passes the request to update a list of messages (with their new embeddings)
     * down to the DAO.
     */
    suspend fun updateMessages(messages: List<Message>) {
        messageDao.updateMessages(messages)
    }

    /**
     * Passes the request to delete all messages for a contact down to the DAO.
     */
    suspend fun deleteContactHistory(contactName: String) {
        messageDao.deleteMessagesForContact(contactName)
    }

    suspend fun isContactImported(contactName: String): Boolean {
        // The DAO returns 0 if no contact is found, and 1 if found.
        // We check if the result is greater than 0.
        return messageDao.isContactImported(contactName) > 0
    }
}

